Agregando transacciones al ejecutar scripts de migración de la base de datos (#7646)
# Description

Se agrega un wrapper al momento de ejecutar los scripts de migración de
la base de datos.

Esto deberá ayudar a hacer rollback a los cambios ejecutados en un
script en caso de que algun query falle dentro del mismo.

El rollback tendría que permitir volver a ejecutar nuevamente el script
si es que este llegara a tener fallas.

Fixes: #7613

# Comments

Al ejecutar el script aún veo el traceback del error:
```bash
Traceback (most recent call last):
  File "/opt/omegaup/stuff/database_utils.py", line 112, in mysql
    return subprocess.check_output(args,
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/mysql', '--defaults-file=/home/ubuntu/.my.cnf', 'omegaup', '-NBe', 'source /opt/omegaup/frontend/database/00222_add_timestamp_user_and_school_ranks.sql;']' returned non-zero exit status 1.
2024-06-07 20:18:41,919:db-migrate.py:Transaction rolled back due to  error in script '/opt/omegaup/frontend/database/00222_add_timestamp_user_and_school_ranks.sql': ERROR 3780 (HY000) at line 6 in file: '/opt/omegaup/frontend/database/00222_add_timestamp_user_and_school_ranks.sql': Referencing column 'country_id' and referenced column 'country_id' in foreign key constraint 'fk_sr_country_id' are incompatible.

Traceback (most recent call last):
  File "/opt/omegaup/stuff/db-migrate.py", line 599, in <module>
    main()
  File "/opt/omegaup/stuff/db-migrate.py", line 595, in main
    args.func(args, auth)
  File "/opt/omegaup/stuff/db-migrate.py", line 311, in migrate
    database_utils.mysql(
  File "/opt/omegaup/stuff/database_utils.py", line 112, in mysql
    return subprocess.check_output(args,
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/mysql', '--defaults-file=/home/ubuntu/.my.cnf', 'omegaup', '-NBe', 'source /opt/omegaup/frontend/database/00222_add_timestamp_user_and_school_ranks.sql;']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/omegaup/./stuff/bootstrap-environment.py", line 311, in <module>
    _main()
  File "/opt/omegaup/./stuff/bootstrap-environment.py", line 302, in _main
    subprocess.check_call(db_migrate_args +
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/omegaup/stuff/db-migrate.py', '--kill-blocking-connections', 'migrate', '--development-environment']' returned non-zero exit status 1.
```
y sólo esperaría ver la excepción que estoy atrapando. En cuanto lo
arregle, subo el cambio.

El rollback funciona correctamente.

# Checklist:

- [x] The code follows the [coding
guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines)
of omegaUp.
- [x] The tests were executed and all of them passed.